### ISSUE TITLE
Project Value

### ISSUE THREAD

**Issue by timgdavies** [open-contracting/public-private-partnerships#23]
Field I.3 of the disclosure framework asks for 'Project value' - although project value is not defined in the framework.

As a working definition, we are looking at using:

"The project value is the total amount invested into the project by both public and private parties." 

The guidance will then point to the budget forecast breakdown extension which can be used to model different parties investments and revenue projections in more detail.

**Comment by dc-coder** [comment]
I think for project value there is:

- **Estimated project value:** the one when project is being prepared, still in pipeline. This may change multiple time.

- **Project Value:** the one on contract signature

- **Re-Negotiated Project Value:** when there are re-negotations, project value or distribution of value among parties might change

I know we can keep track of this in the different releases, but since project value is such an important thing, i wonder if those 3 project values will be captured in 3 fields or just your general thoughts on this.

**Comment by timgdavies** [comment]
You are right that there are these different values, and they will be captured in different places.

I was thinking mainly about project value in the 'Basic project information' section at the moment - which falls under "Pre-procurement" information - hence assuming the estimate, which, as you say, may change a number of times. 

When it comes to contract signature, we have ```contract.value```. I was thinking we could just use the simple field from OCDS at this point, but I wonder if this will also need a more complex structure (e.g. private party commitment, government commitment)? 

Will come to that soon...

**Comment by duncandewhurst** [comment]
The [PPP certification glossary](https://ppp-certification.com/ppp-certification-guide/glossary) gives the following definition for contract value:

> The volume of capital expenditures (Capex) estimated by the procuring authority. It sometimes refers to the total amount of payments to be made by the procuring authority if the bid equals the ceiling on payments.

**Comment by timgdavies** [comment]
Note - value changes over time.

- Need value at financial close
- Need value at implementation (e.g. for cost over-runs)
