### ISSUE TITLE
Risk allocations

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#31]
The [ppp disclosure framework](http://pubdocs.worldbank.org/en/773541448296707678/Disclosure-in-PPPs-Framework.pdf) includes a table for risk allocation (page 50) with a listing of risk types.

We should model this as structured data with an associated codelist of risk types.

The draft modelling shows two example risks for a toll road ppp:

**Draft modelling:**

```json
"riskAllocation": [
	{
		"id" : "1",
		"type" : "demand",
		"description" : "Actual toll revenues are less than those forecast.",
		"allocation" : "publicAuthority",
		"mitigation" : "The Department for Transport will provide an Additional Availability Support Grant in the event that actual toll revenues are less than those forecast."
	},
	{
		"id" : "2",
		"type" : "preConstruction",
		"description" : "Planning permission for the project is not granted.",
		"allocation" : "privateParty",
		"mitigation" : "A planning strategy was agreed with the local planning authority and was shared with the bidders to mitigate planning risk to acceptable levels."
	}
]
```

**Draft codelist**

Risk(s) from framework | Proposed code(s)
--------------------|-----------------
Pre-construction risk: all risks up to financial close | preConstruction
Construction/completion | construction
Cost risk: capital, operating | capitalCost, operatingCost
Refinancing risk | refinancing
Risk related to change in law, taxes, scope, technical standards, regulatory framework | legislative, scope, standards, regulatory
Exchange rate risk | exchangeRate
Operating risk | operating
Commercial risk, market risk, demand risk | commercial, market, demand
Performance risk | performance
Financial risk | financial
Force majeure risk | forceMajeure

**Key Questions**
* Is the proposed modelling sufficient for the types of analysis carried out on risk allocation?

**Comment by dc-coder** [comment]
From first look - i think the risk allocation need to have a money value attached to them.

The budget people usually need to know what money is being allocated to risks - so they can account for them in their budgets. They usually use this data to produce high reports about how much risk the govt. is taking and to make some decisions in budgets etc.

The other thing is, don't we need to model risks based on multiple time intervals? (like risk for a certain element in first 5 years might be less than risks in the next 10 years) and some risks might kick in at specific time of operation of the project...etc.

**Comment by timgdavies** [comment]
We've been looking at the [Public-Private Partnerships Fiscal Risk Assessment Model](http://www.worldbank.org/en/topic/publicprivatepartnerships/brief/ppp-tools#T2), and in particular the 'IN_Detailed Risk Assessment' tab.

This includes structured information on risk, but not detailed financials.

It categorises risk by:

* Allocation (mostly government, shared, mostly private)
* Likelihood (low, medium, high)
* Fiscal impact (low, medium, high)

and asks for whether a mitigation strategy is in place.

The rest of the sheet includes more complex financial modelling, but this feels to be well beyond the scope of an OCDS extension. 

Our suggestion then is to:

* Extend the draft model above with likelihood and fiscal impact codes
* Propose that publishers link out to more advanced financial modelling of actual cost numbers on risk

This seems to meet the use-case of discovering which kinds of risks are being bourne by private or public sector, and their relative severity and fiscal impact, but it leaves the detailed financial exposure as an issue for human rather than machine analysis.

**Comment by timgdavies** [comment]
The PFRAM uses the following table of risks:

![image](https://cloud.githubusercontent.com/assets/342624/20142823/48a1c060-a68e-11e6-8954-19ebeacb5b97.png)

**Comment by duncandewhurst** [comment]
There is a [draft extension](https://github.com/open-contracting/ocds-riskAllocation-extension) based on this approach (documentation outstanding).

The proposed codelists (riskCategory, riskAllocation, riskLikelihood, riskImpact) have been added to this [Google Sheet](https://docs.google.com/spreadsheets/d/1qipg79qQReqWgKzn7mRhsriA6V8HCtKkg9GaZO32EUI/edit#gid=1735353039) for consultation.
