### ISSUE TITLE
Merging extension codelists

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#66]
OCDS for PPPs needs to pull together codelists from several locations:

1. Codelists from individual extension repos
2. Codelists in the public-private-partnerships repo itself (e.g. metricID, milestoneCode)
3. Codelists from OCDS core

Currently the ```apply-extensions.py``` script handles case 1. Case 2 is handled by manually dropping these codelists into the ```codelists``` directory. Case 3 isn't currently handled, i.e. core codelists aren't pulled into the public-private-partnerships repo.

Codelists from case 1 and case 2 might 'patch' (i.e. add or remove codes) to existing codelists from cases 1, 2 and 3. 

**Example - the partyRole codelist:**

> OCDS for PPPs uses some codes from the ```partyRole``` codelist in OCDS core (case 3)
>OCDS for PPPs also removes some codes from the core ```partyRole``` codelist and adds some others (case 2)
>OCDS for PPPs also uses the enquiries extension, which adds a code to the ```partyRole``` codelist (case 1)

>So we have a situation where the ```partyRole``` codelist for OCDS for PPPs needs to be built from 3 separate ```partyRole.csv``` files.

@kindly @edugomez would either of you be able to take a look before Friday to help with:

1. the correct syntax/naming convention for using codelist csvs to add/remove codes from existing codelists
2. refactoring the public-private-partnerships repository so it is clear which codelists are being pulled in by apply-extensions.py and which 'belong' in the repo anyway (i.e. case 2 above)
3. adding a column to the built codelists to indicate which extension each code came from
4. updating the apply-extensions.py script to handle cases 1, 2 and 3

@timgdavies can take a look on Friday if you don't have capacity, but thoughts on 1. would be welcome!

**Comment by kindly** [comment]
@duncandewhurst 
**1.**
For this +filename.csv ,-filename.csv should be used if adding or removing items from a codelist.
**2.**
I think there needs to be 3 directories here:
- One that lives in extension docs directory like in the core standard this contains the raw codelists from the extension itself (i.e with the + and -)
- One that belongs to the ppp extension itself in the codelists directory.
- One named compiledCodelists that will compile all the codelists together for the docs.  These codelists will be translated as codelists (not as sphinx code)

Next steps are for @duncandewhurst to remove codelists from the "codelists" directory on the "66-codelist-refactor" branch that belong to extensions not ppp itself:
https://github.com/open-contracting/public-private-partnerships/tree/66-codelist-refactor/codelists
and to make sure the ordering of the extensions are correct in apply-extensions.py

Then I will update apply-extensions.py to make the compiledCodelists and put them in that directory and make sure the docs a wired up to use that directory instead of the "codelists" directory.

**Comment by duncandewhurst** [comment]
thanks @kindly 

I've updated the 66-codelist-refactor branch so it only has the codelists that belong to the ppp extension itself and to move the ppp extension to the end of the merging order

There are a couple of outstanding issues to resolve before building the docs:

* outstanding [issue](https://github.com/open-contracting/standard/issues/471
) with milestoneType codelist in OCDS core
* outstanding [PR](https://github.com/open-contracting/ocds_qualification_extension/pull/2) on qualification extension to add releaseTag codelist

There is an outstanding PR https://github.com/open-contracting/public-private-partnerships/pull/65 on the public-private-partnerships repo which contains some doc fixes which need merging in but also includes a couple of codelist related commits which are superceded by the work done on the 66-codelist-refactor branch, so I could do with some help unpicking that.

**Comment by duncandewhurst** [comment]
The issue with the milestoneType codelist has been resolved in https://github.com/open-contracting/standard/compare/471-milestone-type

I have updated the 66-codelist-refactor branch to reflect that
