### ISSUE TITLE
Docs build errors - unknown options, missing files

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/public-private-partnerships#67]
@Bjwebb I am getting a few errors in the docs build process for OCDS for PPPs, would you mind taking a quick look and giving me some pointers?

I think some of these might be down to Sphinx directive options which are supported in the core docs build but not in the ppp docs build, e.g.

```
public-private-partnerships\docs\extensions\bids.md:1: ERROR: Error in "extensiontable" directive:
unknown option: "exclude_definitions".

.. extensiontable::
   :extension: bids
   :exclude_definitions: Bids Bid
```

There are also some errors due to missing files on the individual extension pages, I think this might be down to where either the build process or apply-extensions.py copies the extension codelists to, e.g.

```
public-private-partnerships\docs\extensions\bids.md:1: SEVERE: Problems with "csv-table" directive pat
h:
[Errno 2] No such file or directory: '../standard/docs/en/extensions/codelists/bidStatistics.csv'.

.. csv-table::
   :header-rows: 1
   :file: standard/docs/en/extensions/codelists/bidStatistics.csv
```
and
```
public-private-partnerships\docs\reference\documents.md:1: SEVERE: Problems with "csv-table" directive
 path:
[Errno 2] No such file or directory: '../../../codelists/documentType.csv'.

.. csv-table::
   :header-rows: 1
   :file: ../../codelists/documentType.csv
```
There are also these two errors with the include_only option which I haven't been able to get to the bottom of:
```
public-private-partnerships\docs\framework.md:1: ERROR: No table data detected in CSV file.

.. jsoninclude-flat:: examples/full.json
  :jsonpointer: /releases/1/tender
  :include_only: contractPeriod

public-private-partnerships\docs\framework.md:1: ERROR: No table data detected in CSV file.

.. jsoninclude-flat:: examples/full.json
  :jsonpointer: /releases/1/tender
  :include_only: contractPeriod
  :ignore_path: /releases/1/
```

**Comment by Bjwebb** [comment]
> I think some of these might be down to Sphinx directive options which are supported in the core docs build but not in the ppp docs build, e.g.

Yes. I've split these out into a new repo, so we can keep track of the latest code more easily - https://github.com/open-contracting/ocds_sphinx_directives - and done the necessary changes to pull these in.

> There are also some errors due to missing files on the individual extension pages, I think this might be down to where either the build process or apply-extensions.py copies the extension codelists to, e.g.

Yes, this is to do with codelist location. The trickiest issue here is probably that the codelist location is different for the main docs and the PPP docs, which is a problem when the file is coming from an extension repo. I also have some codelist location (and other) updates to extensions in the main OCDS docs that I still need to feed back to the individual repos. Could do with talking to @kindly and/or @timgdavies to sort out what we want to do here.

> There are also these two errors with the include_only option which I haven't been able to get to the bottom of:

The problem is that contractPeriod is an object, but it look lke the code doesn't show children. Changing the jsonpointer to /releases/1/tender/contractPeriod fixes it.

I've made a pull request for my changes https://github.com/open-contracting/public-private-partnerships/pull/68
