### ISSUE TITLE
Incorrect link to latest version when viewing older version

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/public-private-partnerships#88]
http://standard.open-contracting.org/profiles/ppp/theme/en/ has an alert linking to:

http://standard.open-contracting.org/latest/en/

But it should link to:

http://standard.open-contracting.org/profiles/ppp/latest/en/

**Comment by dc-coder** [comment]
The default readme of this repo links to http://ocds-for-ppps.readthedocs.io/en/latest/
But it should link to:
http://standard.open-contracting.org/profiles/ppp/latest/en/

**Comment by duncandewhurst** [comment]
@Bjwebb would you be able to take a look at the issue with the alert please?

https://github.com/open-contracting/public-private-partnerships/commit/703abbf32c1b6ae9b06764a80de47b6de9c8bf9b resolves the issue with the link in the readme

**Comment by Bjwebb** [comment]
The alert is on an old branch (`theme`): http://standard.open-contracting.org/profiles/ppp/theme/en/
If you look at the latest master it's correct: http://standard.open-contracting.org/profiles/ppp/master/en/
Options:
* Leave the old branch alone, it's old and therefore allowed to be wrong
* Retrigger a build on https://travis-ci.org/open-contracting/public-private-partnerships/builds/267898225 (will work since the error is in the theme, raises questions of what branches we make this effort for) 
* Delete it (would leave a 404 that looks like http://standard.open-contracting.org/profiles/ppp/notabranch/en/, raises questions of if/when we delete old branches generally)

**Comment by jpmckinney** [comment]
I'll take option 1 (leave things alone) :)
