### ISSUE TITLE
broken link to milestones in I.10. Project approval dates

### ISSUE THREAD

**Issue by dc-coder** [open-contracting/public-private-partnerships#89]
On this page
http://standard.open-contracting.org/profiles/ppp/latest/en/framework/#i-10-project-approval-dates

> Dates of various approvals
> This information can be provided using the milestones extension.

milestones extension points to http://standard.open-contracting.org/profiles/ppp/latest/extensions/milestones which is a broken link, not even a 404

**Comment by duncandewhurst** [comment]
@Bjwebb would you be able to take a look at this please?

The links are working OK in my local build, but broken (missing the /en/) in the travis build

**Comment by Bjwebb** [comment]
I think I've fixed this in https://github.com/open-contracting/public-private-partnerships/pull/97 by replacing `../../` with `../`. This may have been working locally, because these are equivalent if you're only one step up from the domain e.g. http://localhost:8000/framework/../../ == http://localhost:8000/framework/../ == http://localhost:8000/.

**Comment by duncandewhurst** [comment]
thanks @Bjwebb
